.Sh DESCRIPTION
disctl may be used to introspect and control the state of systemd services. On a machine with a running
.Ic disnix
service, disctl will operate on services deployed via
.Ic disenv
\(em those with a disnix-xxx..-service prefix.

.Sh COPYRIGHT
Copyright \(co 2016 Deakin Software and Technology Innovation Lab

.Sh SEE ALSO
.Xr disenv 1 ,
.Xr systemctl 1
